# Generated by Django 4.2.5 on 2023-11-11 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0005_delete_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='jobs')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('qualification', models.CharField(choices=[('BSC', 'BSc'), ('BBA', 'BBA'), ('Btech', 'B.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('MSC', 'MSC'), ('Mtech', 'M.Tech'), ('Diploma', 'Diploma'), ('ITI', 'ITI'), ('OTHER', 'Other')], max_length=20)),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=5)),
                ('skills', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.joblist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
