# Generated by Django 4.2.5 on 2023-11-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField()),
                ('Job_name', models.CharField(max_length=200)),
                ('Company_name', models.CharField(max_length=200)),
                ('Company_Address', models.CharField(max_length=300)),
                ('Company_Location', models.CharField(blank=True, max_length=300, null=True)),
                ('Job_description', models.CharField(max_length=300)),
                ('Salary_range1', models.CharField(max_length=200)),
                ('Salary_range2', models.CharField(max_length=200)),
                ('Job_type', models.CharField(choices=[('PartTime', 'PartTime'), ('FullTime', 'FullTime')], default='FullTime', max_length=200)),
                ('Prefered_location', models.CharField(choices=[('Kerala', 'Kerala'), ('Bengaluru', 'Bengaluru'), ('Chennai', 'Chennai'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai')], default='Kerala', max_length=200)),
                ('Experience_level', models.CharField(choices=[('Internship', 'Internship'), ('Trainee', 'Trainee'), ('Fresher', 'Fresher'), ('Experienced', 'Experienced')], default='Fresher', max_length=200)),
                ('Apply_link', models.CharField(max_length=200)),
                ('Qualification', models.CharField(max_length=200)),
                ('Responsibility', models.CharField(max_length=200)),
                ('last_date', models.DateTimeField()),
                ('Company_image', models.ImageField(blank=True, null=True, upload_to='jobs')),
            ],
        ),
    ]
