# Generated by Django 4.2.5 on 2023-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='Vaccancy',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
