# Generated by Django 4.2.5 on 2023-11-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=5),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='qualification',
            field=models.CharField(choices=[('BSC', 'BSc'), ('IT', 'IT'), ('Non IT', 'Non IT'), ('BBA', 'BBA'), ('Btech', 'B.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('MSC', 'MSC'), ('Mtech', 'M.Tech'), ('Diploma', 'Diploma'), ('ITI', 'ITI'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
