# Generated by Django 4.2.5 on 2023-11-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_alter_jobapplication_experience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
