# Generated by Django 4.2.5 on 2023-12-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0009_remove_employee_company_remove_employee_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
